### ISSUE TITLE
Remote REST API endpoints

### ISSUE THREAD

**Issue by Raruto** [afragen/git-remote-updater#3]
Why not just save remote GHU REST API endpoints in database instead of downloading JSON config files?

**Comment by afragen** [comment]
The JSON config file is meant for a consumption by a different site, ideally localhost. The REST endpoints were designed to use with [Git Remote Updater](https://github.com/afragen/git-remote-updater).

The endpoints are meant to be dynamic as they reflect which plugin/theme is installed and which branch.

**Comment by Raruto** [comment]
> The JSON config file is meant for a consumption by a different site, ideally localhost. The REST endpoints were designed to use with Git Remote Updater.

I already understood that, what I currently don't understand is the need to use JSON files instead of connecting directly to **GHU Clients** through the existing url exposed by the client.


To better understand, within your **GRU Server**, instead of saving the following json file:
```js
{
  "site": {
    "host": "https://example.com",
    "rest_namespace_route": "github-updater/v1/repos/",
    "rest_api_key": "c5i7tys26be3we0ziz8o2wgbs07me6c2"
  }
}
```

Why not just save the following database option? 

`"https://example.com/github-updater/v1/repos/?key=c5i7tys26be3we0ziz8o2wgbs07me6c2"`

_Doing so, to manage multiple clients, it would be enough to save them within a textarea with one URL element per line_

**Comment by afragen** [comment]
What’s the benefit of saving this to the database. Remember an update would be necessary anytime the REST API key is updated. 

I designed this part to be able to remotely PUSH updates via the webhook. My thought was that it makes more sense to have these as config file rather than database entries. It also means I get to avoid one more settings tab/page.

**Comment by afragen** [comment]
The other benefit is to avoid copy/paste errors.

**Comment by Raruto** [comment]
> What’s the benefit of saving this to the database.

Certainly both solutions have their pros and cons.

Here are some of my thoughts:
- if you use a public web server you must also worry about making that folder inaccessible.
- if you don't have ftp access to your server you cannot upload these configuration files.
- all plugin configurations reside in the same place (this way you can create complete DB Backups).
- you can easily manage everything via admin dashboard (eg. token updates).
- GHU and GRU token handling should work in a similar way (lower barrier to entry for newcomers).

> Remember an update would be necessary anytime the REST API key is updated.

- Since this can potentially happen several times in using the program, it would be better to have a unique workflow

> The other benefit is to avoid copy/paste errors.

- If you really worry about this, we could just use a **JSON File importer / exporter** (instead of relying on static config files)

**Comment by afragen** [comment]
When I initially thought of how to do this I was thinking of a settings page and storing in the database but, the simplicity of a JSON config file won out. 

I’m at work and on mobile. I’ll try to address your other points soon.

**Comment by afragen** [comment]
It would seem what we need to do is create a database table and manage it via WP_List_Tables. 

Ideally some framework to add/manage this would be best. Still investigating.

**Comment by Raruto** [comment]
Below some alternative solutions using javascript:

- https://codepen.io/rajaovi/pen/NNNpoR ( **Pure JS** )
- https://www.jqueryscript.net/demo/Editable-Tables-jQuery-Bootstrap-Bootstable/ ( **jQuery + Bootstrap** )
- https://codepen.io/ashblue/pen/mCtuA ( **jQuery + Bootstrap Export** )

_you can just save the table as a single [JSON string](https://stackoverflow.com/questions/41870551/saving-string-to-database-in-wordpress) instead of handling complex DBs..._

**Comment by afragen** [comment]
I think I've figured out how to do this. Now I just need to code it.

Have I said lately how much I dislike the Settings API? 😣

**Comment by Raruto** [comment]
> Have I said lately how much I dislike the Settings API? 😣

Well, let's say that a **PHP-only** solution is not exactly the best way to handle user forms ...

> I think I've figured out how to do this. Now I just need to code it.

Will use a dedicated page (aka _settings.php_) for the settings?

**Comment by afragen** [comment]
I know you'll might not like it but it will use a tabbed interface. I prefer not to have my plugin pages spread around in different locations.

**Comment by Raruto** [comment]
Ok, but just out of curiosity: **settings.php** vs **tools.php**?

_( ..evil laugh.. )_

**Comment by afragen** [comment]
> Ok, but just out of curiosity: **settings.php** vs **tools.php**?
> 
> _( ..evil laugh.. )_

Tools because the primary usage was functional.

**Comment by afragen** [comment]
<img width="1419" alt="screenshot_08" src="https://user-images.githubusercontent.com/1296790/72390093-c2610800-36de-11ea-9368-a8568a4830d8.png">

**Comment by afragen** [comment]
Still a few things left to do.

**Comment by Raruto** [comment]
> Still a few things left to do.

From what I can see it seems functional. Nice job!

> Tools because the primary usage was functional.

Not a very strong reason, but I agree on the choice.

Anyway, that's also why i think this [plugin](https://github.com/afragen/github-updater/issues/838) is inserted in the wrong menu (it has more features than settings!)

To avoid kilometric discussions, couldn't we make that the relative **settings.php** menu directly opens the relative **settings tab** inside GHU / GRU ? (a kind of bookmark..)

_You know what I mean?_

**Comment by afragen** [comment]
Actually I think I need more coffee, I'm not quite sure what you mean.

Are you suggesting an actual menu inside the Settings menu that opens up the real Settings tab inside the Tools menu? It's an interesting thought. 

_Is there prior art?_

**Comment by Raruto** [comment]
> Are you suggesting an actual menu inside the Settings menu that opens up the real Settings tab inside the Tools menu? It's an interesting thought.

Something like that, at least it could be a good compromise... 😄 

> _Is there prior art?_

It seems that within the [`create_admin_page`](https://github.com/afragen/github-updater/blob/a956811342eadc9cc3c990d7e8c97fe491c77f35/src/GitHub_Updater/Settings.php#L231) callback function, we can already access some information related to the actual parent page (more info: [_add_submenu_page_](https://developer.wordpress.org/reference/functions/add_submenu_page/#notes))

After that, we just need to set the right url tab...

**Comment by afragen** [comment]
As I'm having issues with the WP_List_Table bulk actions being returned to page with a tab query arg I may need another solution anyways. 😒 I like nice neat packages.

**Comment by afragen** [comment]
I think this plugin is basically feature complete and functional.

I think GHU belongs in Settings menu because its mostly set it and forget it. Occasionally visiting tabs to install stuff.  But I know you disagree. 🙃

**Comment by Raruto** [comment]
Ok, although these are the personal beliefs...

We could have a filter within the [`add_plugin_page`](https://github.com/afragen/github-updater/blob/a956811342eadc9cc3c990d7e8c97fe491c77f35/src/GitHub_Updater/Settings.php#L185) function? (to easily override those parameters)

**Comment by afragen** [comment]
I thought about this and I think I agree with you. Let me know what you think.

**Comment by Raruto** [comment]
> I thought about this and I think I agree with you. Let me know what you think.

Much cleaner than hundreds of tabs. 👍
