### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by shanebp** [afragen/git-remote-updater#5]
Anyone else getting these emails from github when using this plugin to pull updates? 
Is there a common solution? 

> On February 10th, 2020 at 15:55 (UTC) your personal access token xxxxx using WordPress/5.3.2; https://xxx.com was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/repositories/11239863/zipball/9.3.1
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

**Comment by shanebp** [comment]
Sorry, wrong repo. 
And this issue is known on https://github.com/afragen/github-updater/issues

**Comment by afragen** [comment]
And it is a fixed issue. 😉
