### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by reggieofarrell** [afragen/git-remote-updater#6]
Hi Andy.  I'm trying to use this with some staging sites that have Basic Auth enabled via NGINX.  Those sites don't show up, so I assume it's not supported currently.  I tried passing the user and pass in the url like...

https://user:pass@example.com

...but no love there either.  Is that an issue with my server config, or just something that's not supported currently?

**Comment by afragen** [comment]
So what you need to remember is that the actual update processing is handled by GitHub Updater, which does currently support Basic Auth authentication.

In order for Git Remote Update to work correctly, the updates must work correctly on the site when using GitHub Updater.

**Comment by afragen** [comment]
FWIW my local dev environment is Local Beta using nginx.

**Comment by reggieofarrell** [comment]
I'm using SpinupWP to manage this server.  I'll ask Delicious Brains about it.  When I try to access the site directly in the browser by putting the user and pass in the URL it also still blocks me and asks for the creds.  I think it's something todo with the NGINX config.  I'll report back.

**Comment by afragen** [comment]
I also use SpinupWP so I know it's tested here.

Do you have the current release of GitHub Updater properly installed and functioning on the site?

**Comment by reggieofarrell** [comment]
I think so.  It's on 9.3.2.  Seems to be working properly.

**Comment by afragen** [comment]
So updates occur on the site's dashboard? You will likely have to purge the object cache while testing this.

Let's make sure that GHU works on the site first. Then we can figure out if there are any issues with Git Remote Updater.

BTW, I usually run the Git Remote Update from a local dev environment. It doesn't need to be on a server unless team management would necessitate that.

**Comment by afragen** [comment]
Easiest way to test whether GHU is working is to locally decrease the plugin version number, and an update will show.

**Comment by afragen** [comment]
Have you read, https://thefragens.com/git-remote-updater-the-personal-remote-management-system/

**Comment by reggieofarrell** [comment]
Just read that, and I will try your plugin version test right now.  Thanks.

**Comment by reggieofarrell** [comment]
Tested.  GHU is working properly on that staging site

**Comment by reggieofarrell** [comment]
It also connects to the git-remote-updater instance just fine when I turn Basic Auth off

**Comment by afragen** [comment]
~What do you mean when you say turn Basic Auth off?~

**Comment by afragen** [comment]
I just looked in my SpinupWP dashboard and see what you mean.

I've never tested with a site that isn't directly accessible. I guess the question is can your site be accessed via `curl` and what does the command look like?

**Comment by reggieofarrell** [comment]
`curl` does work...

`curl -u username:password https://example.com` works

**Comment by afragen** [comment]
problem is that  GitHub Updater authenticates using a Basic Auth header and you can't have 2 at the same time. 😝

**Comment by afragen** [comment]
https://stackoverflow.com/questions/29282578/multiple-http-authorization-headers

https://stackoverflow.com/questions/3761845/multiple-authentication-schemes-for-http-authorization-header

https://stackoverflow.com/questions/22229996/basic-http-and-bearer-token-authentication
