### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by allrite** [afragen/git-remote-updater#7]
When I attempt to activate the git-remote-updater I get:

Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected ')' in /srv/www/mainwp.csiro.au/html/wp-content/plugins/git-remote-updater/src/Git_Remote_Updater/Settings.php on line 62

Version 0.5.2, both master and develop branches.

**Comment by afragen** [comment]
Hmm, checking now on a fresh install.

**Comment by afragen** [comment]
Odd, I just installed on a fresh install, GitHub Updater develop branch and Git Remote Updater master branch are the only plugins installed. Everything worked as expected.

I did install Git Remote Updater via the Install Plugin tab on GitHub Updater. You can ensure both are installed correctly by ensuring that the directories in `wp-content/plugins/` are `github-updater` and `git-remote-updater`.

**Comment by afragen** [comment]
FWIW, that error makes no sense as the `)` is the closing paren of the `add_submenu_command`

https://github.com/afragen/git-remote-updater/blob/b57a05bcd5d88ee899af2acf1168d116705b5410/src/Git_Remote_Updater/Settings.php#L55-L62

**Comment by afragen** [comment]
FWIW I usually run Git Remote Updater from a local environment. I simply found it easier, however, I also run it from a server.

**Comment by allrite** [comment]
I'll try it on my local machine as well, but it would be good to run it from a central server so that others can access the update if I'm unavailable. Haven't had a chance to further test this as have been busy doing the github-updater updates on about 30 sites, which also involve some setting changes on each site and a bit of other maintenance that a central tool can't perform.

**Comment by allrite** [comment]
I deleted the commas on the ends of lines 61 and 70 in git-remote-updater/src/Git_Remote_Updater/Settings.php (dev version) and the plugin now installs. FWIW VS Code was showing them as errors.

I was getting the same error across multiple instances of WP when I attempted to install and activate the remote plugin on them (to check if it would install).

**Comment by afragen** [comment]
Thanks, fixed in https://github.com/afragen/git-remote-updater/commit/2b5aa9364fbe1564dcdfe89745a041fd0d20bf73

I have no idea why it seems to work on all my sites and why my install of VSCode didn't show an error.

**Comment by afragen** [comment]
What extension showed that error?

**Comment by allrite** [comment]
Probably Felix Becker's PHP Debug extension.

**Comment by afragen** [comment]
Hmm, must be another as I have that one installed. 🤨

**Comment by afragen** [comment]
LMK if you have any questions about setting it up. You should see feedback within the Update page and it will log to the error log of the site where the update happened.
