### ISSUE TITLE
not updating to latest tag

### ISSUE THREAD

**Issue by reggieofarrell** [afragen/git-remote-updater#8]
I'm having an issue where `git-remote-updater` isn't updating connected sites to the latest tag.  The theme in questions is currently tagged at 1.5.8, and I can see in wp-admin on the sites that have the theme installed that the theme has an update available, but if I try to update them via `git-remote-updater` it keeps re-installing v1.5.7.  The tag and version in style.css in the theme match.  Any ideas?

Git Remote Udater: v0.5.3
GitHub Updater: v9.6.1 or greater

**Comment by afragen** [comment]
Can you share the theme URL?

**Comment by afragen** [comment]
Git Remote Updater isn't designed to use the tag to update. It's designed to use the branch. Not sure if that might be the issue.

**Comment by afragen** [comment]
If you need updates based on the latest tag I can consider this a feature request. 😉

**Comment by reggieofarrell** [comment]
The theme repo is private and not under my account.  I do think that is the issue though.  We recently started using tags on the theme and I think this is our first time trying to update all the sites with Git Remote Updater since then.  So... sure!  Let's call it a feature request.

**Comment by afragen** [comment]
Should I assume that your tag is a built release asset and not just a zipfile of the primary branch? That will make a difference.

**Comment by afragen** [comment]
Do you have the `Release Asset` header set in the theme? It might be helpful if you could paste the theme headers here.

**Comment by reggieofarrell** [comment]
We've been creating releases, yes.  So if it's easier to implement that way, we could keep doing that.  We do not have the `Release Asset` header set currently...

```Theme Name: FitForm Base Theme
Theme URI: https://github.com/fitform/fitform-base-theme
Author: Reggie O'Farrell
GitHub Theme URI: https://github.com/fitform/fitform-base-theme
Description: Base theme for FitForm Wordpress sites.
Version: 1.5.8
Text Domain: fitform
```

**Comment by afragen** [comment]
Is there some fundamental difference between a release and the branch it's based on?

For instance, GitHub Updater has a release based on the master branch and updates based on the branch work fine.

**Comment by afragen** [comment]
What error are you getting? I wonder if it has to do with authentication.

**Comment by reggieofarrell** [comment]
> Is there some fundamental difference between a release and the branch it's based on?
> 
> For instance, GitHub Updater has a release based on the master branch and updates based on the branch work fine.

No difference really.  Releases are based on the master branch.  Pretty much whatever is in master is identical to the current release.

> What error are you getting? I wonder if it has to do with authentication.

Not getting an error.  Git Remote Updater is just not pulling the current release (1.5.8).  It's pulling 1.5.7.  I just checked the debug.log on one of the sites.  The only thing I'm seeing in regards to GitHub Updater is a warning...

```
PHP Warning:  file_get_contents(/tmp/711ebaca5b239bdbd24194b29045b28c-tmp-readme.txt): failed to open stream: No such file or directory
```

I just made the repo public temporarily so you can have a look...

https://github.com/fitform/fitform-base-theme

**Comment by reggieofarrell** [comment]
So...  I actually just ran it again and it pull in 1.5.8.  Maybe some caching or transient issue?  If so, which end would it be on, the remote site, or the site with Git Remote Updater?  I did just change the repo to public as well though.

**Comment by reggieofarrell** [comment]
Also, just reading on this `Release Asset` header.  We can't use that header because we use branch switching on our staging sites to test new features.

**Comment by afragen** [comment]
If there's no build process then you really don't need a release asset.

**Comment by afragen** [comment]
In Git Remote Updater the response is shown after an update attempt. Is there an error noted here?

**Comment by reggieofarrell** [comment]
> If there's no build process then you really don't need a release asset.

No build process currently, although at some point in the future there may be.  The servers are SpinupWP managed too though, so it would be easy to use their deploy script functionality to do any of that if need be

> In Git Remote Updater the response is shown after an update attempt. Is there an error noted here?

No error.

**Comment by afragen** [comment]
I just checked/tested and I have a private theme that uses a release asset for updating. It updates correctly using Git Remote Updater. I also tested a private repository an it updates correctly too.

Let's circle back. My understanding is that you pushed an update to your theme using Git Remote Updater, but the theme didn't update?

**Comment by afragen** [comment]
This is what I get if I 'update' your theme from v1.5.7

```
thefragens.net: fitform-base-theme
Downloading update from https://api.github.com/repos/fitform/fitform-base-theme/zipball/1.5.8…
Unpacking the update…
Installing the latest version…
Removing the old version of the theme…
Theme updated successfully.
```

As you can see it uses the latest tag.

**Comment by afragen** [comment]
This is what I get if the theme is current, not _requiring_ an update.

```
thefragens.net: fitform-base-theme
Downloading update from https://api.github.com/repos/fitform/fitform-base-theme/zipball/master…
Unpacking the update…
Installing the latest version…
Removing the old version of the theme…
Theme updated successfully.
```

Here it uses the branch as GitHub Updater's cache is still valid.

**Comment by reggieofarrell** [comment]
Correct...  Thinking back, this one time was one different to how I was previously doing it.  This time I just pushed a tag for the new version (1.5.8) rather than creating a release because I realized that we didn't actually need releases and pushing tags is easier.  So the first time I tried the update via Git Remote Updater, the current release was 1.5.7 and the current tag was 1.5.8.  When that didn't pull down 1.5.8, I tried creating a release because I thought maybe there was an issue with the release and tag not matching up anymore.  After creating the new release, I got the same behavior...  1.5.7 was installed.  

However, when I tried again just a bit ago, 1.5.8 was pulled in correctly.  

Does Git Remote Updater force a download of the latest tag, or is there a cache involved that maybe hadn't expired yet?

**Comment by afragen** [comment]
Hmm.

Git Remote Updater seems to correctly push the current version in the repository. Git Remote Updater only requires that updating and/or branch switching works correctly in the site using GitHub Updater.

**Comment by afragen** [comment]
Git Remote Updater does cache it's REST API call to your site but only for 5 minutes. You can see the data it gathers based on the URL listed in the Remote Management tab and using `repos` instead of `update` in that URL.

**Comment by afragen** [comment]
You can alter this cache timeout with the following filter.

```php
add_filter(
	'git_remote_updater_repo_transient_timeout',
	function () {
		return 5;
	}
);
```

This sets the timeout to 5 seconds. I use it for testing.

**Comment by afragen** [comment]
I'm currently working on a feature to use the tag for updating if the current branch is the primary branch.

**Comment by afragen** [comment]
So using the latest `develop` branches of both GitHub Updater and Git Remote Updater, any updates using Git Remote Updater to the primary branch will use the most current tag, if tagging is used.

With no update available, you can see below that the pushed update uses the tag.

```
thefragens.net: fitform-base-theme
Downloading update from https://api.github.com/repos/fitform/fitform-base-theme/zipball/1.5.8…
Unpacking the update…
Installing the latest version…
Removing the old version of the theme…
Theme updated successfully.
```

**Comment by reggieofarrell** [comment]
@afragen Sorry for not responding.  Crazy week.  I'll try out the develop branch here.  Thanks.

**Comment by afragen** [comment]
You can use the `master` branch. I finally made and official release.

You'll still need the `develop` branch of GHU.
